# docker-compose.yml
version: '3.8'

services:
  ezloc-web-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: ezloc-web-app
    environment:
      - NODE_ENV=test
    ports:
      - "8080:8080"
    env_file:
      - .env.test
    volumes:
      - ./src:/home/app/src
    networks:
      - ezloc-network

  # Optional database
  ezloc-db:
    container_name: ezloc-db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ezloc-network

networks:
  ezloc-network:
    driver: bridge

volumes:
  postgres_data:
