# docker-compose.yml
version: '3.8'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: web-app
    environment:
      - NODE_ENV=test
    ports:
      - "8080:8080"
    env_file:
      - .env.test
    volumes:
      - ./src:/opt/app/src
      - ./tests:/opt/app/tests
      - ./public:/opt/app/public
    networks:
      - default

networks:
  default:
    driver: bridge

