apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: web-app

profiles:
  - name: minikube
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: ntdtfr/ezloc-web-app
          context: .
          docker:
            dockerfile: Dockerfile
            target: development
            buildArgs:
              #NODE_VERSION: "22"
              NODE_ENV: development
          sync:
            infer:
              - "**/*.ts"
      local:
        useBuildkit: true
        concurrency: 0
    deploy: &deploy
      kubectl: {}
    manifests: &manifests
      rawYaml:
        - k8s/*.yml
    portForward: &portForward
      - resourceType: service
        resourceName: web-app-service
        port: 8080
        localPort: 8080
    activation:
      - kubeContext: minikube

  - name: gke
    build:
      tagPolicy:
        sha256: {}
      googleCloudBuild:
        workerPool: projects/ezloc/locations/europe-west1-b/workerPools/worker-development-pool
        projectId: ezloc-02
        concurrency: 0
      artifacts:
        - image: ntdtfr/ezloc-web-app
          kaniko:
            dockerfile: Dockerfile
            target: development
            cache: {}
    deploy: *deploy
    manifests: *manifests
    portForward: *portForward
    activation:
      - kubeContext: gke_ezloc-02_europe-west1-b_development-cluster
