---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: ntdtfr/ezloc-web-app
          # env:
          #   - name: NODE_ENV
          #     value: "development"
          ports:
            - name: http
              containerPort: 8080
