---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
    app: web-app-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: web-app
